apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-app
spec:
  type: NodePort
  selector:
    app: front-app
  ports:
    - name: http
      nodePort: 30000
      port: 3000
      targetPort: 3000
      protocol: TCP
